// Code generated by go-swagger; DO NOT EDIT.

package repo_creds_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// CreateRepositoryCredentialsReader is a Reader for the CreateRepositoryCredentials structure.
type CreateRepositoryCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRepositoryCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateRepositoryCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateRepositoryCredentialsOK creates a CreateRepositoryCredentialsOK with default headers values
func NewCreateRepositoryCredentialsOK() *CreateRepositoryCredentialsOK {
	return &CreateRepositoryCredentialsOK{}
}

/*CreateRepositoryCredentialsOK handles this case with default header values.

(empty)
*/
type CreateRepositoryCredentialsOK struct {
	Payload *models.V1alpha1RepoCreds
}

func (o *CreateRepositoryCredentialsOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/repocreds][%d] createRepositoryCredentialsOK  %+v", 200, o.Payload)
}

func (o *CreateRepositoryCredentialsOK) GetPayload() *models.V1alpha1RepoCreds {
	return o.Payload
}

func (o *CreateRepositoryCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RepoCreds)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
