// Code generated by go-swagger; DO NOT EDIT.

package repo_creds_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// NewCreateRepositoryCredentialsParams creates a new CreateRepositoryCredentialsParams object
// with the default values initialized.
func NewCreateRepositoryCredentialsParams() *CreateRepositoryCredentialsParams {
	var ()
	return &CreateRepositoryCredentialsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRepositoryCredentialsParamsWithTimeout creates a new CreateRepositoryCredentialsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateRepositoryCredentialsParamsWithTimeout(timeout time.Duration) *CreateRepositoryCredentialsParams {
	var ()
	return &CreateRepositoryCredentialsParams{

		timeout: timeout,
	}
}

// NewCreateRepositoryCredentialsParamsWithContext creates a new CreateRepositoryCredentialsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateRepositoryCredentialsParamsWithContext(ctx context.Context) *CreateRepositoryCredentialsParams {
	var ()
	return &CreateRepositoryCredentialsParams{

		Context: ctx,
	}
}

// NewCreateRepositoryCredentialsParamsWithHTTPClient creates a new CreateRepositoryCredentialsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateRepositoryCredentialsParamsWithHTTPClient(client *http.Client) *CreateRepositoryCredentialsParams {
	var ()
	return &CreateRepositoryCredentialsParams{
		HTTPClient: client,
	}
}

/*CreateRepositoryCredentialsParams contains all the parameters to send to the API endpoint
for the create repository credentials operation typically these are written to a http.Request
*/
type CreateRepositoryCredentialsParams struct {

	/*Body*/
	Body *models.V1alpha1RepoCreds

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create repository credentials params
func (o *CreateRepositoryCredentialsParams) WithTimeout(timeout time.Duration) *CreateRepositoryCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create repository credentials params
func (o *CreateRepositoryCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create repository credentials params
func (o *CreateRepositoryCredentialsParams) WithContext(ctx context.Context) *CreateRepositoryCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create repository credentials params
func (o *CreateRepositoryCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create repository credentials params
func (o *CreateRepositoryCredentialsParams) WithHTTPClient(client *http.Client) *CreateRepositoryCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create repository credentials params
func (o *CreateRepositoryCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create repository credentials params
func (o *CreateRepositoryCredentialsParams) WithBody(body *models.V1alpha1RepoCreds) *CreateRepositoryCredentialsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create repository credentials params
func (o *CreateRepositoryCredentialsParams) SetBody(body *models.V1alpha1RepoCreds) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRepositoryCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
