// Code generated by go-swagger; DO NOT EDIT.

package repo_creds_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// ListRepositoryCredentialsReader is a Reader for the ListRepositoryCredentials structure.
type ListRepositoryCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListRepositoryCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListRepositoryCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListRepositoryCredentialsOK creates a ListRepositoryCredentialsOK with default headers values
func NewListRepositoryCredentialsOK() *ListRepositoryCredentialsOK {
	return &ListRepositoryCredentialsOK{}
}

/*ListRepositoryCredentialsOK handles this case with default header values.

(empty)
*/
type ListRepositoryCredentialsOK struct {
	Payload *models.V1alpha1RepoCredsList
}

func (o *ListRepositoryCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/repocreds][%d] listRepositoryCredentialsOK  %+v", 200, o.Payload)
}

func (o *ListRepositoryCredentialsOK) GetPayload() *models.V1alpha1RepoCredsList {
	return o.Payload
}

func (o *ListRepositoryCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RepoCredsList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
