// Code generated by go-swagger; DO NOT EDIT.

package repo_creds_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// NewUpdateRepositoryCredentialsParams creates a new UpdateRepositoryCredentialsParams object
// with the default values initialized.
func NewUpdateRepositoryCredentialsParams() *UpdateRepositoryCredentialsParams {
	var ()
	return &UpdateRepositoryCredentialsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateRepositoryCredentialsParamsWithTimeout creates a new UpdateRepositoryCredentialsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateRepositoryCredentialsParamsWithTimeout(timeout time.Duration) *UpdateRepositoryCredentialsParams {
	var ()
	return &UpdateRepositoryCredentialsParams{

		timeout: timeout,
	}
}

// NewUpdateRepositoryCredentialsParamsWithContext creates a new UpdateRepositoryCredentialsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateRepositoryCredentialsParamsWithContext(ctx context.Context) *UpdateRepositoryCredentialsParams {
	var ()
	return &UpdateRepositoryCredentialsParams{

		Context: ctx,
	}
}

// NewUpdateRepositoryCredentialsParamsWithHTTPClient creates a new UpdateRepositoryCredentialsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateRepositoryCredentialsParamsWithHTTPClient(client *http.Client) *UpdateRepositoryCredentialsParams {
	var ()
	return &UpdateRepositoryCredentialsParams{
		HTTPClient: client,
	}
}

/*UpdateRepositoryCredentialsParams contains all the parameters to send to the API endpoint
for the update repository credentials operation typically these are written to a http.Request
*/
type UpdateRepositoryCredentialsParams struct {

	/*Body*/
	Body *models.V1alpha1RepoCreds
	/*CredsURL*/
	CredsURL string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) WithTimeout(timeout time.Duration) *UpdateRepositoryCredentialsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) WithContext(ctx context.Context) *UpdateRepositoryCredentialsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) WithHTTPClient(client *http.Client) *UpdateRepositoryCredentialsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) WithBody(body *models.V1alpha1RepoCreds) *UpdateRepositoryCredentialsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) SetBody(body *models.V1alpha1RepoCreds) {
	o.Body = body
}

// WithCredsURL adds the credsURL to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) WithCredsURL(credsURL string) *UpdateRepositoryCredentialsParams {
	o.SetCredsURL(credsURL)
	return o
}

// SetCredsURL adds the credsUrl to the update repository credentials params
func (o *UpdateRepositoryCredentialsParams) SetCredsURL(credsURL string) {
	o.CredsURL = credsURL
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRepositoryCredentialsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param creds.url
	if err := r.SetPathParam("creds.url", o.CredsURL); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
