// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// CreateMixin8Reader is a Reader for the CreateMixin8 structure.
type CreateMixin8Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateMixin8Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateMixin8OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateMixin8OK creates a CreateMixin8OK with default headers values
func NewCreateMixin8OK() *CreateMixin8OK {
	return &CreateMixin8OK{}
}

/*CreateMixin8OK handles this case with default header values.

(empty)
*/
type CreateMixin8OK struct {
	Payload *models.V1alpha1Application
}

func (o *CreateMixin8OK) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications][%d] createMixin8OK  %+v", 200, o.Payload)
}

func (o *CreateMixin8OK) GetPayload() *models.V1alpha1Application {
	return o.Payload
}

func (o *CreateMixin8OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
