// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// DeleteMixin8Reader is a Reader for the DeleteMixin8 structure.
type DeleteMixin8Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMixin8Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMixin8OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteMixin8OK creates a DeleteMixin8OK with default headers values
func NewDeleteMixin8OK() *DeleteMixin8OK {
	return &DeleteMixin8OK{}
}

/*DeleteMixin8OK handles this case with default header values.

(empty)
*/
type DeleteMixin8OK struct {
	Payload models.ApplicationApplicationResponse
}

func (o *DeleteMixin8OK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/applications/{name}][%d] deleteMixin8OK  %+v", 200, o.Payload)
}

func (o *DeleteMixin8OK) GetPayload() models.ApplicationApplicationResponse {
	return o.Payload
}

func (o *DeleteMixin8OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
