// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteMixin8Params creates a new DeleteMixin8Params object
// with the default values initialized.
func NewDeleteMixin8Params() *DeleteMixin8Params {
	var ()
	return &DeleteMixin8Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMixin8ParamsWithTimeout creates a new DeleteMixin8Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteMixin8ParamsWithTimeout(timeout time.Duration) *DeleteMixin8Params {
	var ()
	return &DeleteMixin8Params{

		timeout: timeout,
	}
}

// NewDeleteMixin8ParamsWithContext creates a new DeleteMixin8Params object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteMixin8ParamsWithContext(ctx context.Context) *DeleteMixin8Params {
	var ()
	return &DeleteMixin8Params{

		Context: ctx,
	}
}

// NewDeleteMixin8ParamsWithHTTPClient creates a new DeleteMixin8Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteMixin8ParamsWithHTTPClient(client *http.Client) *DeleteMixin8Params {
	var ()
	return &DeleteMixin8Params{
		HTTPClient: client,
	}
}

/*DeleteMixin8Params contains all the parameters to send to the API endpoint
for the delete mixin8 operation typically these are written to a http.Request
*/
type DeleteMixin8Params struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete mixin8 params
func (o *DeleteMixin8Params) WithTimeout(timeout time.Duration) *DeleteMixin8Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete mixin8 params
func (o *DeleteMixin8Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete mixin8 params
func (o *DeleteMixin8Params) WithContext(ctx context.Context) *DeleteMixin8Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete mixin8 params
func (o *DeleteMixin8Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete mixin8 params
func (o *DeleteMixin8Params) WithHTTPClient(client *http.Client) *DeleteMixin8Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete mixin8 params
func (o *DeleteMixin8Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete mixin8 params
func (o *DeleteMixin8Params) WithName(name string) *DeleteMixin8Params {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete mixin8 params
func (o *DeleteMixin8Params) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMixin8Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
