// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// DeleteResourceReader is a Reader for the DeleteResource structure.
type DeleteResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteResourceOK creates a DeleteResourceOK with default headers values
func NewDeleteResourceOK() *DeleteResourceOK {
	return &DeleteResourceOK{}
}

/*DeleteResourceOK handles this case with default header values.

(empty)
*/
type DeleteResourceOK struct {
	Payload models.ApplicationApplicationResponse
}

func (o *DeleteResourceOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/applications/{name}/resource][%d] deleteResourceOK  %+v", 200, o.Payload)
}

func (o *DeleteResourceOK) GetPayload() models.ApplicationApplicationResponse {
	return o.Payload
}

func (o *DeleteResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
