// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// GetApplicationSyncWindowsReader is a Reader for the GetApplicationSyncWindows structure.
type GetApplicationSyncWindowsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetApplicationSyncWindowsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetApplicationSyncWindowsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetApplicationSyncWindowsOK creates a GetApplicationSyncWindowsOK with default headers values
func NewGetApplicationSyncWindowsOK() *GetApplicationSyncWindowsOK {
	return &GetApplicationSyncWindowsOK{}
}

/*GetApplicationSyncWindowsOK handles this case with default header values.

(empty)
*/
type GetApplicationSyncWindowsOK struct {
	Payload *models.ApplicationApplicationSyncWindowsResponse
}

func (o *GetApplicationSyncWindowsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/syncwindows][%d] getApplicationSyncWindowsOK  %+v", 200, o.Payload)
}

func (o *GetApplicationSyncWindowsOK) GetPayload() *models.ApplicationApplicationSyncWindowsResponse {
	return o.Payload
}

func (o *GetApplicationSyncWindowsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationApplicationSyncWindowsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
