// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetApplicationSyncWindowsParams creates a new GetApplicationSyncWindowsParams object
// with the default values initialized.
func NewGetApplicationSyncWindowsParams() *GetApplicationSyncWindowsParams {
	var ()
	return &GetApplicationSyncWindowsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetApplicationSyncWindowsParamsWithTimeout creates a new GetApplicationSyncWindowsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetApplicationSyncWindowsParamsWithTimeout(timeout time.Duration) *GetApplicationSyncWindowsParams {
	var ()
	return &GetApplicationSyncWindowsParams{

		timeout: timeout,
	}
}

// NewGetApplicationSyncWindowsParamsWithContext creates a new GetApplicationSyncWindowsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetApplicationSyncWindowsParamsWithContext(ctx context.Context) *GetApplicationSyncWindowsParams {
	var ()
	return &GetApplicationSyncWindowsParams{

		Context: ctx,
	}
}

// NewGetApplicationSyncWindowsParamsWithHTTPClient creates a new GetApplicationSyncWindowsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetApplicationSyncWindowsParamsWithHTTPClient(client *http.Client) *GetApplicationSyncWindowsParams {
	var ()
	return &GetApplicationSyncWindowsParams{
		HTTPClient: client,
	}
}

/*GetApplicationSyncWindowsParams contains all the parameters to send to the API endpoint
for the get application sync windows operation typically these are written to a http.Request
*/
type GetApplicationSyncWindowsParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get application sync windows params
func (o *GetApplicationSyncWindowsParams) WithTimeout(timeout time.Duration) *GetApplicationSyncWindowsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get application sync windows params
func (o *GetApplicationSyncWindowsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get application sync windows params
func (o *GetApplicationSyncWindowsParams) WithContext(ctx context.Context) *GetApplicationSyncWindowsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get application sync windows params
func (o *GetApplicationSyncWindowsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get application sync windows params
func (o *GetApplicationSyncWindowsParams) WithHTTPClient(client *http.Client) *GetApplicationSyncWindowsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get application sync windows params
func (o *GetApplicationSyncWindowsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get application sync windows params
func (o *GetApplicationSyncWindowsParams) WithName(name string) *GetApplicationSyncWindowsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get application sync windows params
func (o *GetApplicationSyncWindowsParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetApplicationSyncWindowsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
