// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// GetManifestsReader is a Reader for the GetManifests structure.
type GetManifestsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetManifestsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetManifestsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetManifestsOK creates a GetManifestsOK with default headers values
func NewGetManifestsOK() *GetManifestsOK {
	return &GetManifestsOK{}
}

/*GetManifestsOK handles this case with default header values.

(empty)
*/
type GetManifestsOK struct {
	Payload *models.RepositoryManifestResponse
}

func (o *GetManifestsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/manifests][%d] getManifestsOK  %+v", 200, o.Payload)
}

func (o *GetManifestsOK) GetPayload() *models.RepositoryManifestResponse {
	return o.Payload
}

func (o *GetManifestsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RepositoryManifestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
