// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// ListResourceActionsReader is a Reader for the ListResourceActions structure.
type ListResourceActionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListResourceActionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListResourceActionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListResourceActionsOK creates a ListResourceActionsOK with default headers values
func NewListResourceActionsOK() *ListResourceActionsOK {
	return &ListResourceActionsOK{}
}

/*ListResourceActionsOK handles this case with default header values.

(empty)
*/
type ListResourceActionsOK struct {
	Payload *models.ApplicationResourceActionsListResponse
}

func (o *ListResourceActionsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/resource/actions][%d] listResourceActionsOK  %+v", 200, o.Payload)
}

func (o *ListResourceActionsOK) GetPayload() *models.ApplicationResourceActionsListResponse {
	return o.Payload
}

func (o *ListResourceActionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationResourceActionsListResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
