// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// ListResourceEventsReader is a Reader for the ListResourceEvents structure.
type ListResourceEventsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListResourceEventsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListResourceEventsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListResourceEventsOK creates a ListResourceEventsOK with default headers values
func NewListResourceEventsOK() *ListResourceEventsOK {
	return &ListResourceEventsOK{}
}

/*ListResourceEventsOK handles this case with default header values.

(empty)
*/
type ListResourceEventsOK struct {
	Payload *models.V1EventList
}

func (o *ListResourceEventsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/events][%d] listResourceEventsOK  %+v", 200, o.Payload)
}

func (o *ListResourceEventsOK) GetPayload() *models.V1EventList {
	return o.Payload
}

func (o *ListResourceEventsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1EventList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
