// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListResourceActionsParams creates a new ListResourceActionsParams object
// with the default values initialized.
func NewListResourceActionsParams() *ListResourceActionsParams {
	var ()
	return &ListResourceActionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListResourceActionsParamsWithTimeout creates a new ListResourceActionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListResourceActionsParamsWithTimeout(timeout time.Duration) *ListResourceActionsParams {
	var ()
	return &ListResourceActionsParams{

		timeout: timeout,
	}
}

// NewListResourceActionsParamsWithContext creates a new ListResourceActionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListResourceActionsParamsWithContext(ctx context.Context) *ListResourceActionsParams {
	var ()
	return &ListResourceActionsParams{

		Context: ctx,
	}
}

// NewListResourceActionsParamsWithHTTPClient creates a new ListResourceActionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListResourceActionsParamsWithHTTPClient(client *http.Client) *ListResourceActionsParams {
	var ()
	return &ListResourceActionsParams{
		HTTPClient: client,
	}
}

/*ListResourceActionsParams contains all the parameters to send to the API endpoint
for the list resource actions operation typically these are written to a http.Request
*/
type ListResourceActionsParams struct {

	/*Group*/
	Group *string
	/*Kind*/
	Kind *string
	/*Name*/
	Name string
	/*Namespace*/
	Namespace *string
	/*ResourceName*/
	ResourceName *string
	/*Version*/
	Version *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list resource actions params
func (o *ListResourceActionsParams) WithTimeout(timeout time.Duration) *ListResourceActionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list resource actions params
func (o *ListResourceActionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list resource actions params
func (o *ListResourceActionsParams) WithContext(ctx context.Context) *ListResourceActionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list resource actions params
func (o *ListResourceActionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list resource actions params
func (o *ListResourceActionsParams) WithHTTPClient(client *http.Client) *ListResourceActionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list resource actions params
func (o *ListResourceActionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroup adds the group to the list resource actions params
func (o *ListResourceActionsParams) WithGroup(group *string) *ListResourceActionsParams {
	o.SetGroup(group)
	return o
}

// SetGroup adds the group to the list resource actions params
func (o *ListResourceActionsParams) SetGroup(group *string) {
	o.Group = group
}

// WithKind adds the kind to the list resource actions params
func (o *ListResourceActionsParams) WithKind(kind *string) *ListResourceActionsParams {
	o.SetKind(kind)
	return o
}

// SetKind adds the kind to the list resource actions params
func (o *ListResourceActionsParams) SetKind(kind *string) {
	o.Kind = kind
}

// WithName adds the name to the list resource actions params
func (o *ListResourceActionsParams) WithName(name string) *ListResourceActionsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the list resource actions params
func (o *ListResourceActionsParams) SetName(name string) {
	o.Name = name
}

// WithNamespace adds the namespace to the list resource actions params
func (o *ListResourceActionsParams) WithNamespace(namespace *string) *ListResourceActionsParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the list resource actions params
func (o *ListResourceActionsParams) SetNamespace(namespace *string) {
	o.Namespace = namespace
}

// WithResourceName adds the resourceName to the list resource actions params
func (o *ListResourceActionsParams) WithResourceName(resourceName *string) *ListResourceActionsParams {
	o.SetResourceName(resourceName)
	return o
}

// SetResourceName adds the resourceName to the list resource actions params
func (o *ListResourceActionsParams) SetResourceName(resourceName *string) {
	o.ResourceName = resourceName
}

// WithVersion adds the version to the list resource actions params
func (o *ListResourceActionsParams) WithVersion(version *string) *ListResourceActionsParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the list resource actions params
func (o *ListResourceActionsParams) SetVersion(version *string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *ListResourceActionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Group != nil {

		// query param group
		var qrGroup string
		if o.Group != nil {
			qrGroup = *o.Group
		}
		qGroup := qrGroup
		if qGroup != "" {
			if err := r.SetQueryParam("group", qGroup); err != nil {
				return err
			}
		}

	}

	if o.Kind != nil {

		// query param kind
		var qrKind string
		if o.Kind != nil {
			qrKind = *o.Kind
		}
		qKind := qrKind
		if qKind != "" {
			if err := r.SetQueryParam("kind", qKind); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Namespace != nil {

		// query param namespace
		var qrNamespace string
		if o.Namespace != nil {
			qrNamespace = *o.Namespace
		}
		qNamespace := qrNamespace
		if qNamespace != "" {
			if err := r.SetQueryParam("namespace", qNamespace); err != nil {
				return err
			}
		}

	}

	if o.ResourceName != nil {

		// query param resourceName
		var qrResourceName string
		if o.ResourceName != nil {
			qrResourceName = *o.ResourceName
		}
		qResourceName := qrResourceName
		if qResourceName != "" {
			if err := r.SetQueryParam("resourceName", qResourceName); err != nil {
				return err
			}
		}

	}

	if o.Version != nil {

		// query param version
		var qrVersion string
		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := qrVersion
		if qVersion != "" {
			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
