// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// ListMixin8Reader is a Reader for the ListMixin8 structure.
type ListMixin8Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListMixin8Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListMixin8OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListMixin8OK creates a ListMixin8OK with default headers values
func NewListMixin8OK() *ListMixin8OK {
	return &ListMixin8OK{}
}

/*ListMixin8OK handles this case with default header values.

(empty)
*/
type ListMixin8OK struct {
	Payload *models.V1alpha1ApplicationList
}

func (o *ListMixin8OK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications][%d] listMixin8OK  %+v", 200, o.Payload)
}

func (o *ListMixin8OK) GetPayload() *models.V1alpha1ApplicationList {
	return o.Payload
}

func (o *ListMixin8OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1ApplicationList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
