// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// PatchResourceReader is a Reader for the PatchResource structure.
type PatchResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchResourceOK creates a PatchResourceOK with default headers values
func NewPatchResourceOK() *PatchResourceOK {
	return &PatchResourceOK{}
}

/*PatchResourceOK handles this case with default header values.

(empty)
*/
type PatchResourceOK struct {
	Payload *models.ApplicationApplicationResourceResponse
}

func (o *PatchResourceOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications/{name}/resource][%d] patchResourceOK  %+v", 200, o.Payload)
}

func (o *PatchResourceOK) GetPayload() *models.ApplicationApplicationResourceResponse {
	return o.Payload
}

func (o *PatchResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ApplicationApplicationResourceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
