// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// NewPatchParams creates a new PatchParams object
// with the default values initialized.
func NewPatchParams() *PatchParams {
	var ()
	return &PatchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchParamsWithTimeout creates a new PatchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchParamsWithTimeout(timeout time.Duration) *PatchParams {
	var ()
	return &PatchParams{

		timeout: timeout,
	}
}

// NewPatchParamsWithContext creates a new PatchParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchParamsWithContext(ctx context.Context) *PatchParams {
	var ()
	return &PatchParams{

		Context: ctx,
	}
}

// NewPatchParamsWithHTTPClient creates a new PatchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchParamsWithHTTPClient(client *http.Client) *PatchParams {
	var ()
	return &PatchParams{
		HTTPClient: client,
	}
}

/*PatchParams contains all the parameters to send to the API endpoint
for the patch operation typically these are written to a http.Request
*/
type PatchParams struct {

	/*Body*/
	Body *models.ApplicationApplicationPatchRequest
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch params
func (o *PatchParams) WithTimeout(timeout time.Duration) *PatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch params
func (o *PatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch params
func (o *PatchParams) WithContext(ctx context.Context) *PatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch params
func (o *PatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch params
func (o *PatchParams) WithHTTPClient(client *http.Client) *PatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch params
func (o *PatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch params
func (o *PatchParams) WithBody(body *models.ApplicationApplicationPatchRequest) *PatchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch params
func (o *PatchParams) SetBody(body *models.ApplicationApplicationPatchRequest) {
	o.Body = body
}

// WithName adds the name to the patch params
func (o *PatchParams) WithName(name string) *PatchParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch params
func (o *PatchParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
