// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchResourceParams creates a new PatchResourceParams object
// with the default values initialized.
func NewPatchResourceParams() *PatchResourceParams {
	var ()
	return &PatchResourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchResourceParamsWithTimeout creates a new PatchResourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchResourceParamsWithTimeout(timeout time.Duration) *PatchResourceParams {
	var ()
	return &PatchResourceParams{

		timeout: timeout,
	}
}

// NewPatchResourceParamsWithContext creates a new PatchResourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchResourceParamsWithContext(ctx context.Context) *PatchResourceParams {
	var ()
	return &PatchResourceParams{

		Context: ctx,
	}
}

// NewPatchResourceParamsWithHTTPClient creates a new PatchResourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchResourceParamsWithHTTPClient(client *http.Client) *PatchResourceParams {
	var ()
	return &PatchResourceParams{
		HTTPClient: client,
	}
}

/*PatchResourceParams contains all the parameters to send to the API endpoint
for the patch resource operation typically these are written to a http.Request
*/
type PatchResourceParams struct {

	/*Body*/
	Body string
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch resource params
func (o *PatchResourceParams) WithTimeout(timeout time.Duration) *PatchResourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch resource params
func (o *PatchResourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch resource params
func (o *PatchResourceParams) WithContext(ctx context.Context) *PatchResourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch resource params
func (o *PatchResourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch resource params
func (o *PatchResourceParams) WithHTTPClient(client *http.Client) *PatchResourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch resource params
func (o *PatchResourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch resource params
func (o *PatchResourceParams) WithBody(body string) *PatchResourceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch resource params
func (o *PatchResourceParams) SetBody(body string) {
	o.Body = body
}

// WithName adds the name to the patch resource params
func (o *PatchResourceParams) WithName(name string) *PatchResourceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the patch resource params
func (o *PatchResourceParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PatchResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
