// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// ResourceTreeReader is a Reader for the ResourceTree structure.
type ResourceTreeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResourceTreeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewResourceTreeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewResourceTreeOK creates a ResourceTreeOK with default headers values
func NewResourceTreeOK() *ResourceTreeOK {
	return &ResourceTreeOK{}
}

/*ResourceTreeOK handles this case with default header values.

(empty)
*/
type ResourceTreeOK struct {
	Payload *models.V1alpha1ApplicationTree
}

func (o *ResourceTreeOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{applicationName}/resource-tree][%d] resourceTreeOK  %+v", 200, o.Payload)
}

func (o *ResourceTreeOK) GetPayload() *models.V1alpha1ApplicationTree {
	return o.Payload
}

func (o *ResourceTreeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1ApplicationTree)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
