// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// RevisionMetadataReader is a Reader for the RevisionMetadata structure.
type RevisionMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RevisionMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRevisionMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRevisionMetadataOK creates a RevisionMetadataOK with default headers values
func NewRevisionMetadataOK() *RevisionMetadataOK {
	return &RevisionMetadataOK{}
}

/*RevisionMetadataOK handles this case with default header values.

(empty)
*/
type RevisionMetadataOK struct {
	Payload *models.V1alpha1RevisionMetadata
}

func (o *RevisionMetadataOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/applications/{name}/revisions/{revision}/metadata][%d] revisionMetadataOK  %+v", 200, o.Payload)
}

func (o *RevisionMetadataOK) GetPayload() *models.V1alpha1RevisionMetadata {
	return o.Payload
}

func (o *RevisionMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RevisionMetadata)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
