// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRevisionMetadataParams creates a new RevisionMetadataParams object
// with the default values initialized.
func NewRevisionMetadataParams() *RevisionMetadataParams {
	var ()
	return &RevisionMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRevisionMetadataParamsWithTimeout creates a new RevisionMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRevisionMetadataParamsWithTimeout(timeout time.Duration) *RevisionMetadataParams {
	var ()
	return &RevisionMetadataParams{

		timeout: timeout,
	}
}

// NewRevisionMetadataParamsWithContext creates a new RevisionMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewRevisionMetadataParamsWithContext(ctx context.Context) *RevisionMetadataParams {
	var ()
	return &RevisionMetadataParams{

		Context: ctx,
	}
}

// NewRevisionMetadataParamsWithHTTPClient creates a new RevisionMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRevisionMetadataParamsWithHTTPClient(client *http.Client) *RevisionMetadataParams {
	var ()
	return &RevisionMetadataParams{
		HTTPClient: client,
	}
}

/*RevisionMetadataParams contains all the parameters to send to the API endpoint
for the revision metadata operation typically these are written to a http.Request
*/
type RevisionMetadataParams struct {

	/*Name*/
	Name string
	/*Revision*/
	Revision string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the revision metadata params
func (o *RevisionMetadataParams) WithTimeout(timeout time.Duration) *RevisionMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the revision metadata params
func (o *RevisionMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the revision metadata params
func (o *RevisionMetadataParams) WithContext(ctx context.Context) *RevisionMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the revision metadata params
func (o *RevisionMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the revision metadata params
func (o *RevisionMetadataParams) WithHTTPClient(client *http.Client) *RevisionMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the revision metadata params
func (o *RevisionMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the revision metadata params
func (o *RevisionMetadataParams) WithName(name string) *RevisionMetadataParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the revision metadata params
func (o *RevisionMetadataParams) SetName(name string) {
	o.Name = name
}

// WithRevision adds the revision to the revision metadata params
func (o *RevisionMetadataParams) WithRevision(revision string) *RevisionMetadataParams {
	o.SetRevision(revision)
	return o
}

// SetRevision adds the revision to the revision metadata params
func (o *RevisionMetadataParams) SetRevision(revision string) {
	o.Revision = revision
}

// WriteToRequest writes these params to a swagger request
func (o *RevisionMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param revision
	if err := r.SetPathParam("revision", o.Revision); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
