// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// SyncReader is a Reader for the Sync structure.
type SyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSyncOK creates a SyncOK with default headers values
func NewSyncOK() *SyncOK {
	return &SyncOK{}
}

/*SyncOK handles this case with default header values.

(empty)
*/
type SyncOK struct {
	Payload *models.V1alpha1Application
}

func (o *SyncOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/applications/{name}/sync][%d] syncOK  %+v", 200, o.Payload)
}

func (o *SyncOK) GetPayload() *models.V1alpha1Application {
	return o.Payload
}

func (o *SyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
