// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// NewSyncParams creates a new SyncParams object
// with the default values initialized.
func NewSyncParams() *SyncParams {
	var ()
	return &SyncParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSyncParamsWithTimeout creates a new SyncParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSyncParamsWithTimeout(timeout time.Duration) *SyncParams {
	var ()
	return &SyncParams{

		timeout: timeout,
	}
}

// NewSyncParamsWithContext creates a new SyncParams object
// with the default values initialized, and the ability to set a context for a request
func NewSyncParamsWithContext(ctx context.Context) *SyncParams {
	var ()
	return &SyncParams{

		Context: ctx,
	}
}

// NewSyncParamsWithHTTPClient creates a new SyncParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSyncParamsWithHTTPClient(client *http.Client) *SyncParams {
	var ()
	return &SyncParams{
		HTTPClient: client,
	}
}

/*SyncParams contains all the parameters to send to the API endpoint
for the sync operation typically these are written to a http.Request
*/
type SyncParams struct {

	/*Body*/
	Body *models.ApplicationApplicationSyncRequest
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sync params
func (o *SyncParams) WithTimeout(timeout time.Duration) *SyncParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sync params
func (o *SyncParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sync params
func (o *SyncParams) WithContext(ctx context.Context) *SyncParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sync params
func (o *SyncParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sync params
func (o *SyncParams) WithHTTPClient(client *http.Client) *SyncParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sync params
func (o *SyncParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the sync params
func (o *SyncParams) WithBody(body *models.ApplicationApplicationSyncRequest) *SyncParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the sync params
func (o *SyncParams) SetBody(body *models.ApplicationApplicationSyncRequest) {
	o.Body = body
}

// WithName adds the name to the sync params
func (o *SyncParams) WithName(name string) *SyncParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the sync params
func (o *SyncParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *SyncParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
