// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewTerminateOperationParams creates a new TerminateOperationParams object
// with the default values initialized.
func NewTerminateOperationParams() *TerminateOperationParams {
	var ()
	return &TerminateOperationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTerminateOperationParamsWithTimeout creates a new TerminateOperationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTerminateOperationParamsWithTimeout(timeout time.Duration) *TerminateOperationParams {
	var ()
	return &TerminateOperationParams{

		timeout: timeout,
	}
}

// NewTerminateOperationParamsWithContext creates a new TerminateOperationParams object
// with the default values initialized, and the ability to set a context for a request
func NewTerminateOperationParamsWithContext(ctx context.Context) *TerminateOperationParams {
	var ()
	return &TerminateOperationParams{

		Context: ctx,
	}
}

// NewTerminateOperationParamsWithHTTPClient creates a new TerminateOperationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewTerminateOperationParamsWithHTTPClient(client *http.Client) *TerminateOperationParams {
	var ()
	return &TerminateOperationParams{
		HTTPClient: client,
	}
}

/*TerminateOperationParams contains all the parameters to send to the API endpoint
for the terminate operation operation typically these are written to a http.Request
*/
type TerminateOperationParams struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the terminate operation params
func (o *TerminateOperationParams) WithTimeout(timeout time.Duration) *TerminateOperationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the terminate operation params
func (o *TerminateOperationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the terminate operation params
func (o *TerminateOperationParams) WithContext(ctx context.Context) *TerminateOperationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the terminate operation params
func (o *TerminateOperationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the terminate operation params
func (o *TerminateOperationParams) WithHTTPClient(client *http.Client) *TerminateOperationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the terminate operation params
func (o *TerminateOperationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the terminate operation params
func (o *TerminateOperationParams) WithName(name string) *TerminateOperationParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the terminate operation params
func (o *TerminateOperationParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *TerminateOperationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
