// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// NewUpdateSpecParams creates a new UpdateSpecParams object
// with the default values initialized.
func NewUpdateSpecParams() *UpdateSpecParams {
	var ()
	return &UpdateSpecParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateSpecParamsWithTimeout creates a new UpdateSpecParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateSpecParamsWithTimeout(timeout time.Duration) *UpdateSpecParams {
	var ()
	return &UpdateSpecParams{

		timeout: timeout,
	}
}

// NewUpdateSpecParamsWithContext creates a new UpdateSpecParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateSpecParamsWithContext(ctx context.Context) *UpdateSpecParams {
	var ()
	return &UpdateSpecParams{

		Context: ctx,
	}
}

// NewUpdateSpecParamsWithHTTPClient creates a new UpdateSpecParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateSpecParamsWithHTTPClient(client *http.Client) *UpdateSpecParams {
	var ()
	return &UpdateSpecParams{
		HTTPClient: client,
	}
}

/*UpdateSpecParams contains all the parameters to send to the API endpoint
for the update spec operation typically these are written to a http.Request
*/
type UpdateSpecParams struct {

	/*Body*/
	Body *models.V1alpha1ApplicationSpec
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update spec params
func (o *UpdateSpecParams) WithTimeout(timeout time.Duration) *UpdateSpecParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update spec params
func (o *UpdateSpecParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update spec params
func (o *UpdateSpecParams) WithContext(ctx context.Context) *UpdateSpecParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update spec params
func (o *UpdateSpecParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update spec params
func (o *UpdateSpecParams) WithHTTPClient(client *http.Client) *UpdateSpecParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update spec params
func (o *UpdateSpecParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update spec params
func (o *UpdateSpecParams) WithBody(body *models.V1alpha1ApplicationSpec) *UpdateSpecParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update spec params
func (o *UpdateSpecParams) SetBody(body *models.V1alpha1ApplicationSpec) {
	o.Body = body
}

// WithName adds the name to the update spec params
func (o *UpdateSpecParams) WithName(name string) *UpdateSpecParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the update spec params
func (o *UpdateSpecParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSpecParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
