// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// NewUpdateMixin8Params creates a new UpdateMixin8Params object
// with the default values initialized.
func NewUpdateMixin8Params() *UpdateMixin8Params {
	var ()
	return &UpdateMixin8Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateMixin8ParamsWithTimeout creates a new UpdateMixin8Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateMixin8ParamsWithTimeout(timeout time.Duration) *UpdateMixin8Params {
	var ()
	return &UpdateMixin8Params{

		timeout: timeout,
	}
}

// NewUpdateMixin8ParamsWithContext creates a new UpdateMixin8Params object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateMixin8ParamsWithContext(ctx context.Context) *UpdateMixin8Params {
	var ()
	return &UpdateMixin8Params{

		Context: ctx,
	}
}

// NewUpdateMixin8ParamsWithHTTPClient creates a new UpdateMixin8Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateMixin8ParamsWithHTTPClient(client *http.Client) *UpdateMixin8Params {
	var ()
	return &UpdateMixin8Params{
		HTTPClient: client,
	}
}

/*UpdateMixin8Params contains all the parameters to send to the API endpoint
for the update mixin8 operation typically these are written to a http.Request
*/
type UpdateMixin8Params struct {

	/*ApplicationMetadataName*/
	ApplicationMetadataName string
	/*Body*/
	Body *models.V1alpha1Application

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update mixin8 params
func (o *UpdateMixin8Params) WithTimeout(timeout time.Duration) *UpdateMixin8Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update mixin8 params
func (o *UpdateMixin8Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update mixin8 params
func (o *UpdateMixin8Params) WithContext(ctx context.Context) *UpdateMixin8Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update mixin8 params
func (o *UpdateMixin8Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update mixin8 params
func (o *UpdateMixin8Params) WithHTTPClient(client *http.Client) *UpdateMixin8Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update mixin8 params
func (o *UpdateMixin8Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApplicationMetadataName adds the applicationMetadataName to the update mixin8 params
func (o *UpdateMixin8Params) WithApplicationMetadataName(applicationMetadataName string) *UpdateMixin8Params {
	o.SetApplicationMetadataName(applicationMetadataName)
	return o
}

// SetApplicationMetadataName adds the applicationMetadataName to the update mixin8 params
func (o *UpdateMixin8Params) SetApplicationMetadataName(applicationMetadataName string) {
	o.ApplicationMetadataName = applicationMetadataName
}

// WithBody adds the body to the update mixin8 params
func (o *UpdateMixin8Params) WithBody(body *models.V1alpha1Application) *UpdateMixin8Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update mixin8 params
func (o *UpdateMixin8Params) SetBody(body *models.V1alpha1Application) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateMixin8Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param application.metadata.name
	if err := r.SetPathParam("application.metadata.name", o.ApplicationMetadataName); err != nil {
		return err
	}

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
