// Code generated by go-swagger; DO NOT EDIT.

package application_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewWatchParams creates a new WatchParams object
// with the default values initialized.
func NewWatchParams() *WatchParams {
	var ()
	return &WatchParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewWatchParamsWithTimeout creates a new WatchParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewWatchParamsWithTimeout(timeout time.Duration) *WatchParams {
	var ()
	return &WatchParams{

		timeout: timeout,
	}
}

// NewWatchParamsWithContext creates a new WatchParams object
// with the default values initialized, and the ability to set a context for a request
func NewWatchParamsWithContext(ctx context.Context) *WatchParams {
	var ()
	return &WatchParams{

		Context: ctx,
	}
}

// NewWatchParamsWithHTTPClient creates a new WatchParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewWatchParamsWithHTTPClient(client *http.Client) *WatchParams {
	var ()
	return &WatchParams{
		HTTPClient: client,
	}
}

/*WatchParams contains all the parameters to send to the API endpoint
for the watch operation typically these are written to a http.Request
*/
type WatchParams struct {

	/*Name
	  the application's name.

	*/
	Name *string
	/*Project
	  the project names to restrict returned list applications.

	*/
	Project []string
	/*Refresh
	  forces application reconciliation if set to true.

	*/
	Refresh *string
	/*ResourceVersion
	  when specified with a watch call, shows changes that occur after that particular version of a resource.

	*/
	ResourceVersion *string
	/*Selector
	  the selector to to restrict returned list to applications only with matched labels.

	*/
	Selector *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the watch params
func (o *WatchParams) WithTimeout(timeout time.Duration) *WatchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the watch params
func (o *WatchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the watch params
func (o *WatchParams) WithContext(ctx context.Context) *WatchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the watch params
func (o *WatchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the watch params
func (o *WatchParams) WithHTTPClient(client *http.Client) *WatchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the watch params
func (o *WatchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the watch params
func (o *WatchParams) WithName(name *string) *WatchParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the watch params
func (o *WatchParams) SetName(name *string) {
	o.Name = name
}

// WithProject adds the project to the watch params
func (o *WatchParams) WithProject(project []string) *WatchParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the watch params
func (o *WatchParams) SetProject(project []string) {
	o.Project = project
}

// WithRefresh adds the refresh to the watch params
func (o *WatchParams) WithRefresh(refresh *string) *WatchParams {
	o.SetRefresh(refresh)
	return o
}

// SetRefresh adds the refresh to the watch params
func (o *WatchParams) SetRefresh(refresh *string) {
	o.Refresh = refresh
}

// WithResourceVersion adds the resourceVersion to the watch params
func (o *WatchParams) WithResourceVersion(resourceVersion *string) *WatchParams {
	o.SetResourceVersion(resourceVersion)
	return o
}

// SetResourceVersion adds the resourceVersion to the watch params
func (o *WatchParams) SetResourceVersion(resourceVersion *string) {
	o.ResourceVersion = resourceVersion
}

// WithSelector adds the selector to the watch params
func (o *WatchParams) WithSelector(selector *string) *WatchParams {
	o.SetSelector(selector)
	return o
}

// SetSelector adds the selector to the watch params
func (o *WatchParams) SetSelector(selector *string) {
	o.Selector = selector
}

// WriteToRequest writes these params to a swagger request
func (o *WatchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	valuesProject := o.Project

	joinedProject := swag.JoinByFormat(valuesProject, "")
	// query array param project
	if err := r.SetQueryParam("project", joinedProject...); err != nil {
		return err
	}

	if o.Refresh != nil {

		// query param refresh
		var qrRefresh string
		if o.Refresh != nil {
			qrRefresh = *o.Refresh
		}
		qRefresh := qrRefresh
		if qRefresh != "" {
			if err := r.SetQueryParam("refresh", qRefresh); err != nil {
				return err
			}
		}

	}

	if o.ResourceVersion != nil {

		// query param resourceVersion
		var qrResourceVersion string
		if o.ResourceVersion != nil {
			qrResourceVersion = *o.ResourceVersion
		}
		qResourceVersion := qrResourceVersion
		if qResourceVersion != "" {
			if err := r.SetQueryParam("resourceVersion", qResourceVersion); err != nil {
				return err
			}
		}

	}

	if o.Selector != nil {

		// query param selector
		var qrSelector string
		if o.Selector != nil {
			qrSelector = *o.Selector
		}
		qSelector := qrSelector
		if qSelector != "" {
			if err := r.SetQueryParam("selector", qSelector); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
