// Code generated by go-swagger; DO NOT EDIT.

package account_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// CanIReader is a Reader for the CanI structure.
type CanIReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CanIReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCanIOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCanIOK creates a CanIOK with default headers values
func NewCanIOK() *CanIOK {
	return &CanIOK{}
}

/*CanIOK handles this case with default header values.

(empty)
*/
type CanIOK struct {
	Payload *models.AccountCanIResponse
}

func (o *CanIOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/account/can-i/{resource}/{action}/{subresource}][%d] canIOK  %+v", 200, o.Payload)
}

func (o *CanIOK) GetPayload() *models.AccountCanIResponse {
	return o.Payload
}

func (o *CanIOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountCanIResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
