// Code generated by go-swagger; DO NOT EDIT.

package account_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// CreateTokenMixin9Reader is a Reader for the CreateTokenMixin9 structure.
type CreateTokenMixin9Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateTokenMixin9Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateTokenMixin9OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateTokenMixin9OK creates a CreateTokenMixin9OK with default headers values
func NewCreateTokenMixin9OK() *CreateTokenMixin9OK {
	return &CreateTokenMixin9OK{}
}

/*CreateTokenMixin9OK handles this case with default header values.

(empty)
*/
type CreateTokenMixin9OK struct {
	Payload *models.AccountCreateTokenResponse
}

func (o *CreateTokenMixin9OK) Error() string {
	return fmt.Sprintf("[POST /api/v1/account/{name}/token][%d] createTokenMixin9OK  %+v", 200, o.Payload)
}

func (o *CreateTokenMixin9OK) GetPayload() *models.AccountCreateTokenResponse {
	return o.Payload
}

func (o *CreateTokenMixin9OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountCreateTokenResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
