// Code generated by go-swagger; DO NOT EDIT.

package account_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// NewCreateTokenMixin9Params creates a new CreateTokenMixin9Params object
// with the default values initialized.
func NewCreateTokenMixin9Params() *CreateTokenMixin9Params {
	var ()
	return &CreateTokenMixin9Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTokenMixin9ParamsWithTimeout creates a new CreateTokenMixin9Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateTokenMixin9ParamsWithTimeout(timeout time.Duration) *CreateTokenMixin9Params {
	var ()
	return &CreateTokenMixin9Params{

		timeout: timeout,
	}
}

// NewCreateTokenMixin9ParamsWithContext creates a new CreateTokenMixin9Params object
// with the default values initialized, and the ability to set a context for a request
func NewCreateTokenMixin9ParamsWithContext(ctx context.Context) *CreateTokenMixin9Params {
	var ()
	return &CreateTokenMixin9Params{

		Context: ctx,
	}
}

// NewCreateTokenMixin9ParamsWithHTTPClient creates a new CreateTokenMixin9Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateTokenMixin9ParamsWithHTTPClient(client *http.Client) *CreateTokenMixin9Params {
	var ()
	return &CreateTokenMixin9Params{
		HTTPClient: client,
	}
}

/*CreateTokenMixin9Params contains all the parameters to send to the API endpoint
for the create token mixin9 operation typically these are written to a http.Request
*/
type CreateTokenMixin9Params struct {

	/*Body*/
	Body *models.AccountCreateTokenRequest
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create token mixin9 params
func (o *CreateTokenMixin9Params) WithTimeout(timeout time.Duration) *CreateTokenMixin9Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create token mixin9 params
func (o *CreateTokenMixin9Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create token mixin9 params
func (o *CreateTokenMixin9Params) WithContext(ctx context.Context) *CreateTokenMixin9Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create token mixin9 params
func (o *CreateTokenMixin9Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create token mixin9 params
func (o *CreateTokenMixin9Params) WithHTTPClient(client *http.Client) *CreateTokenMixin9Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create token mixin9 params
func (o *CreateTokenMixin9Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create token mixin9 params
func (o *CreateTokenMixin9Params) WithBody(body *models.AccountCreateTokenRequest) *CreateTokenMixin9Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create token mixin9 params
func (o *CreateTokenMixin9Params) SetBody(body *models.AccountCreateTokenRequest) {
	o.Body = body
}

// WithName adds the name to the create token mixin9 params
func (o *CreateTokenMixin9Params) WithName(name string) *CreateTokenMixin9Params {
	o.SetName(name)
	return o
}

// SetName adds the name to the create token mixin9 params
func (o *CreateTokenMixin9Params) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTokenMixin9Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
