// Code generated by go-swagger; DO NOT EDIT.

package account_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// DeleteTokenMixin9Reader is a Reader for the DeleteTokenMixin9 structure.
type DeleteTokenMixin9Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteTokenMixin9Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteTokenMixin9OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteTokenMixin9OK creates a DeleteTokenMixin9OK with default headers values
func NewDeleteTokenMixin9OK() *DeleteTokenMixin9OK {
	return &DeleteTokenMixin9OK{}
}

/*DeleteTokenMixin9OK handles this case with default header values.

(empty)
*/
type DeleteTokenMixin9OK struct {
	Payload models.AccountEmptyResponse
}

func (o *DeleteTokenMixin9OK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/account/{name}/token/{id}][%d] deleteTokenMixin9OK  %+v", 200, o.Payload)
}

func (o *DeleteTokenMixin9OK) GetPayload() models.AccountEmptyResponse {
	return o.Payload
}

func (o *DeleteTokenMixin9OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
