// Code generated by go-swagger; DO NOT EDIT.

package certificate_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// CreateCertificateReader is a Reader for the CreateCertificate structure.
type CreateCertificateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCertificateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateCertificateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateCertificateOK creates a CreateCertificateOK with default headers values
func NewCreateCertificateOK() *CreateCertificateOK {
	return &CreateCertificateOK{}
}

/*CreateCertificateOK handles this case with default header values.

(empty)
*/
type CreateCertificateOK struct {
	Payload *models.V1alpha1RepositoryCertificateList
}

func (o *CreateCertificateOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/certificates][%d] createCertificateOK  %+v", 200, o.Payload)
}

func (o *CreateCertificateOK) GetPayload() *models.V1alpha1RepositoryCertificateList {
	return o.Payload
}

func (o *CreateCertificateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1RepositoryCertificateList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
