// Code generated by go-swagger; DO NOT EDIT.

package certificate_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListCertificatesParams creates a new ListCertificatesParams object
// with the default values initialized.
func NewListCertificatesParams() *ListCertificatesParams {
	var ()
	return &ListCertificatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListCertificatesParamsWithTimeout creates a new ListCertificatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListCertificatesParamsWithTimeout(timeout time.Duration) *ListCertificatesParams {
	var ()
	return &ListCertificatesParams{

		timeout: timeout,
	}
}

// NewListCertificatesParamsWithContext creates a new ListCertificatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewListCertificatesParamsWithContext(ctx context.Context) *ListCertificatesParams {
	var ()
	return &ListCertificatesParams{

		Context: ctx,
	}
}

// NewListCertificatesParamsWithHTTPClient creates a new ListCertificatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListCertificatesParamsWithHTTPClient(client *http.Client) *ListCertificatesParams {
	var ()
	return &ListCertificatesParams{
		HTTPClient: client,
	}
}

/*ListCertificatesParams contains all the parameters to send to the API endpoint
for the list certificates operation typically these are written to a http.Request
*/
type ListCertificatesParams struct {

	/*CertSubType
	  The sub type of the certificate to match (protocol dependent, usually only used for ssh certs).

	*/
	CertSubType *string
	/*CertType
	  The type of the certificate to match (ssh or https).

	*/
	CertType *string
	/*HostNamePattern
	  A file-glob pattern (not regular expression) the host name has to match.

	*/
	HostNamePattern *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list certificates params
func (o *ListCertificatesParams) WithTimeout(timeout time.Duration) *ListCertificatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list certificates params
func (o *ListCertificatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list certificates params
func (o *ListCertificatesParams) WithContext(ctx context.Context) *ListCertificatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list certificates params
func (o *ListCertificatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list certificates params
func (o *ListCertificatesParams) WithHTTPClient(client *http.Client) *ListCertificatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list certificates params
func (o *ListCertificatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCertSubType adds the certSubType to the list certificates params
func (o *ListCertificatesParams) WithCertSubType(certSubType *string) *ListCertificatesParams {
	o.SetCertSubType(certSubType)
	return o
}

// SetCertSubType adds the certSubType to the list certificates params
func (o *ListCertificatesParams) SetCertSubType(certSubType *string) {
	o.CertSubType = certSubType
}

// WithCertType adds the certType to the list certificates params
func (o *ListCertificatesParams) WithCertType(certType *string) *ListCertificatesParams {
	o.SetCertType(certType)
	return o
}

// SetCertType adds the certType to the list certificates params
func (o *ListCertificatesParams) SetCertType(certType *string) {
	o.CertType = certType
}

// WithHostNamePattern adds the hostNamePattern to the list certificates params
func (o *ListCertificatesParams) WithHostNamePattern(hostNamePattern *string) *ListCertificatesParams {
	o.SetHostNamePattern(hostNamePattern)
	return o
}

// SetHostNamePattern adds the hostNamePattern to the list certificates params
func (o *ListCertificatesParams) SetHostNamePattern(hostNamePattern *string) {
	o.HostNamePattern = hostNamePattern
}

// WriteToRequest writes these params to a swagger request
func (o *ListCertificatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CertSubType != nil {

		// query param certSubType
		var qrCertSubType string
		if o.CertSubType != nil {
			qrCertSubType = *o.CertSubType
		}
		qCertSubType := qrCertSubType
		if qCertSubType != "" {
			if err := r.SetQueryParam("certSubType", qCertSubType); err != nil {
				return err
			}
		}

	}

	if o.CertType != nil {

		// query param certType
		var qrCertType string
		if o.CertType != nil {
			qrCertType = *o.CertType
		}
		qCertType := qrCertType
		if qCertType != "" {
			if err := r.SetQueryParam("certType", qCertType); err != nil {
				return err
			}
		}

	}

	if o.HostNamePattern != nil {

		// query param hostNamePattern
		var qrHostNamePattern string
		if o.HostNamePattern != nil {
			qrHostNamePattern = *o.HostNamePattern
		}
		qHostNamePattern := qrHostNamePattern
		if qHostNamePattern != "" {
			if err := r.SetQueryParam("hostNamePattern", qHostNamePattern); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
