// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountUpdatePasswordRequest account update password request
//
// swagger:model accountUpdatePasswordRequest
type AccountUpdatePasswordRequest struct {

	// current password
	CurrentPassword string `json:"currentPassword,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// new password
	NewPassword string `json:"newPassword,omitempty"`
}

// Validate validates this account update password request
func (m *AccountUpdatePasswordRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountUpdatePasswordRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountUpdatePasswordRequest) UnmarshalBinary(b []byte) error {
	var res AccountUpdatePasswordRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
