// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationApplicationRollbackRequest application application rollback request
//
// swagger:model applicationApplicationRollbackRequest
type ApplicationApplicationRollbackRequest struct {

	// dry run
	DryRun bool `json:"dryRun,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// prune
	Prune bool `json:"prune,omitempty"`
}

// Validate validates this application application rollback request
func (m *ApplicationApplicationRollbackRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationApplicationRollbackRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationApplicationRollbackRequest) UnmarshalBinary(b []byte) error {
	var res ApplicationApplicationRollbackRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
