// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicationApplicationSyncWindow application application sync window
//
// swagger:model applicationApplicationSyncWindow
type ApplicationApplicationSyncWindow struct {

	// duration
	Duration string `json:"duration,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// manual sync
	ManualSync bool `json:"manualSync,omitempty"`

	// schedule
	Schedule string `json:"schedule,omitempty"`
}

// Validate validates this application application sync window
func (m *ApplicationApplicationSyncWindow) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApplicationApplicationSyncWindow) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicationApplicationSyncWindow) UnmarshalBinary(b []byte) error {
	var res ApplicationApplicationSyncWindow
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
