// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterGoogleAnalyticsConfig cluster google analytics config
//
// swagger:model clusterGoogleAnalyticsConfig
type ClusterGoogleAnalyticsConfig struct {

	// anonymize users
	AnonymizeUsers bool `json:"anonymizeUsers,omitempty"`

	// tracking ID
	TrackingID string `json:"trackingID,omitempty"`
}

// Validate validates this cluster google analytics config
func (m *ClusterGoogleAnalyticsConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterGoogleAnalyticsConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterGoogleAnalyticsConfig) UnmarshalBinary(b []byte) error {
	var res ClusterGoogleAnalyticsConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
