// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectProjectTokenCreateRequest ProjectTokenCreateRequest defines project token creation parameters.
//
// swagger:model projectProjectTokenCreateRequest
type ProjectProjectTokenCreateRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// expiresIn represents a duration in seconds
	ExpiresIn string `json:"expiresIn,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// project
	Project string `json:"project,omitempty"`

	// role
	Role string `json:"role,omitempty"`
}

// Validate validates this project project token create request
func (m *ProjectProjectTokenCreateRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectProjectTokenCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectProjectTokenCreateRequest) UnmarshalBinary(b []byte) error {
	var res ProjectProjectTokenCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
