// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RepositoryManifestResponse repository manifest response
//
// swagger:model repositoryManifestResponse
type RepositoryManifestResponse struct {

	// manifests
	Manifests []string `json:"manifests"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// resolved revision
	Revision string `json:"revision,omitempty"`

	// server
	Server string `json:"server,omitempty"`

	// source type
	SourceType string `json:"sourceType,omitempty"`
}

// Validate validates this repository manifest response
func (m *RepositoryManifestResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RepositoryManifestResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RepositoryManifestResponse) UnmarshalBinary(b []byte) error {
	var res RepositoryManifestResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
