// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RepocredsRepoCredsResponse RepoCredsResponse is a response to most repository credentials requests
//
// swagger:model repocredsRepoCredsResponse
type RepocredsRepoCredsResponse interface{}
