// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RepositoryHelmChart repository helm chart
//
// swagger:model repositoryHelmChart
type RepositoryHelmChart struct {

	// name
	Name string `json:"name,omitempty"`

	// versions
	Versions []string `json:"versions"`
}

// Validate validates this repository helm chart
func (m *RepositoryHelmChart) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RepositoryHelmChart) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RepositoryHelmChart) UnmarshalBinary(b []byte) error {
	var res RepositoryHelmChart
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
