// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1EventSeries EventSeries contain information on series of events, i.e. thing that was/is happening
// continuously for some time.
//
// swagger:model v1EventSeries
type V1EventSeries struct {

	// Number of occurrences in this series up to the last heartbeat time
	Count int32 `json:"count,omitempty"`

	// last observed time
	LastObservedTime *V1MicroTime `json:"lastObservedTime,omitempty"`

	// State of this Series: Ongoing or Finished
	// Deprecated. Planned removal for 1.18
	State string `json:"state,omitempty"`
}

// Validate validates this v1 event series
func (m *V1EventSeries) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastObservedTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1EventSeries) validateLastObservedTime(formats strfmt.Registry) error {

	if swag.IsZero(m.LastObservedTime) { // not required
		return nil
	}

	if m.LastObservedTime != nil {
		if err := m.LastObservedTime.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lastObservedTime")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1EventSeries) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1EventSeries) UnmarshalBinary(b []byte) error {
	var res V1EventSeries
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
