// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ConfigManagementPlugin ConfigManagementPlugin contains config management plugin configuration
//
// swagger:model v1alpha1ConfigManagementPlugin
type V1alpha1ConfigManagementPlugin struct {

	// generate
	Generate *V1alpha1Command `json:"generate,omitempty"`

	// init
	Init *V1alpha1Command `json:"init,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this v1alpha1 config management plugin
func (m *V1alpha1ConfigManagementPlugin) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGenerate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ConfigManagementPlugin) validateGenerate(formats strfmt.Registry) error {

	if swag.IsZero(m.Generate) { // not required
		return nil
	}

	if m.Generate != nil {
		if err := m.Generate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("generate")
			}
			return err
		}
	}

	return nil
}

func (m *V1alpha1ConfigManagementPlugin) validateInit(formats strfmt.Registry) error {

	if swag.IsZero(m.Init) { // not required
		return nil
	}

	if m.Init != nil {
		if err := m.Init.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("init")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ConfigManagementPlugin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ConfigManagementPlugin) UnmarshalBinary(b []byte) error {
	var res V1alpha1ConfigManagementPlugin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
