// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1SyncPolicy SyncPolicy controls when a sync will be performed in response to updates in git
//
// swagger:model v1alpha1SyncPolicy
type V1alpha1SyncPolicy struct {

	// automated
	Automated *V1alpha1SyncPolicyAutomated `json:"automated,omitempty"`

	// Options allow you to specify whole app sync-options
	SyncOptions []string `json:"syncOptions"`
}

// Validate validates this v1alpha1 sync policy
func (m *V1alpha1SyncPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAutomated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1SyncPolicy) validateAutomated(formats strfmt.Registry) error {

	if swag.IsZero(m.Automated) { // not required
		return nil
	}

	if m.Automated != nil {
		if err := m.Automated.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("automated")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1SyncPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1SyncPolicy) UnmarshalBinary(b []byte) error {
	var res V1alpha1SyncPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
