// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1HelmFileParameter HelmFileParameter is a file parameter to a helm template
//
// swagger:model v1alpha1HelmFileParameter
type V1alpha1HelmFileParameter struct {

	// Name is the name of the helm parameter
	Name string `json:"name,omitempty"`

	// Path is the path value for the helm parameter
	Path string `json:"path,omitempty"`
}

// Validate validates this v1alpha1 helm file parameter
func (m *V1alpha1HelmFileParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1HelmFileParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1HelmFileParameter) UnmarshalBinary(b []byte) error {
	var res V1alpha1HelmFileParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
