// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationTree ApplicationTree holds nodes which belongs to the application
//
// swagger:model v1alpha1ApplicationTree
type V1alpha1ApplicationTree struct {

	// Nodes contains list of nodes which either directly managed by the application and children of directly managed nodes.
	Nodes []*V1alpha1ResourceNode `json:"nodes"`

	// OrphanedNodes contains if or orphaned nodes: nodes which are not managed by the app but in the same namespace. List is populated only if orphaned resources enabled in app project.
	OrphanedNodes []*V1alpha1ResourceNode `json:"orphanedNodes"`
}

// Validate validates this v1alpha1 application tree
func (m *V1alpha1ApplicationTree) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNodes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOrphanedNodes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ApplicationTree) validateNodes(formats strfmt.Registry) error {

	if swag.IsZero(m.Nodes) { // not required
		return nil
	}

	for i := 0; i < len(m.Nodes); i++ {
		if swag.IsZero(m.Nodes[i]) { // not required
			continue
		}

		if m.Nodes[i] != nil {
			if err := m.Nodes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1alpha1ApplicationTree) validateOrphanedNodes(formats strfmt.Registry) error {

	if swag.IsZero(m.OrphanedNodes) { // not required
		return nil
	}

	for i := 0; i < len(m.OrphanedNodes); i++ {
		if swag.IsZero(m.OrphanedNodes[i]) { // not required
			continue
		}

		if m.OrphanedNodes[i] != nil {
			if err := m.OrphanedNodes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("orphanedNodes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationTree) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationTree) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationTree
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
