// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1EnvEntry v1alpha1 env entry
//
// swagger:model v1alpha1EnvEntry
type V1alpha1EnvEntry struct {

	// the name, usually uppercase
	Name string `json:"name,omitempty"`

	// the value
	Value string `json:"value,omitempty"`
}

// Validate validates this v1alpha1 env entry
func (m *V1alpha1EnvEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1EnvEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1EnvEntry) UnmarshalBinary(b []byte) error {
	var res V1alpha1EnvEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
