// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1Command Command holds binary path and arguments list
//
// swagger:model v1alpha1Command
type V1alpha1Command struct {

	// args
	Args []string `json:"args"`

	// command
	Command []string `json:"command"`
}

// Validate validates this v1alpha1 command
func (m *V1alpha1Command) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1Command) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1Command) UnmarshalBinary(b []byte) error {
	var res V1alpha1Command
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
