// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationSourceKustomize ApplicationSourceKustomize holds kustomize specific options
//
// swagger:model v1alpha1ApplicationSourceKustomize
type V1alpha1ApplicationSourceKustomize struct {

	// CommonLabels adds additional kustomize commonLabels
	CommonLabels map[string]string `json:"commonLabels,omitempty"`

	// Images are kustomize image overrides
	Images []string `json:"images"`

	// NamePrefix is a prefix appended to resources for kustomize apps
	NamePrefix string `json:"namePrefix,omitempty"`

	// NameSuffix is a suffix appended to resources for kustomize apps
	NameSuffix string `json:"nameSuffix,omitempty"`

	// Version contains optional Kustomize version
	Version string `json:"version,omitempty"`
}

// Validate validates this v1alpha1 application source kustomize
func (m *V1alpha1ApplicationSourceKustomize) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationSourceKustomize) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationSourceKustomize) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationSourceKustomize
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
