// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1HelmParameter HelmParameter is a parameter to a helm template
//
// swagger:model v1alpha1HelmParameter
type V1alpha1HelmParameter struct {

	// ForceString determines whether to tell Helm to interpret booleans and numbers as strings
	ForceString bool `json:"forceString,omitempty"`

	// Name is the name of the helm parameter
	Name string `json:"name,omitempty"`

	// Value is the value for the helm parameter
	Value string `json:"value,omitempty"`
}

// Validate validates this v1alpha1 helm parameter
func (m *V1alpha1HelmParameter) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1HelmParameter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1HelmParameter) UnmarshalBinary(b []byte) error {
	var res V1alpha1HelmParameter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
