// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1JWTToken JWTToken holds the issuedAt and expiresAt values of a token
//
// swagger:model v1alpha1JWTToken
type V1alpha1JWTToken struct {

	// exp
	Exp string `json:"exp,omitempty"`

	// iat
	Iat string `json:"iat,omitempty"`

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this v1alpha1 j w t token
func (m *V1alpha1JWTToken) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1JWTToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1JWTToken) UnmarshalBinary(b []byte) error {
	var res V1alpha1JWTToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
