// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ConnectionState ConnectionState contains information about remote resource connection state
//
// swagger:model v1alpha1ConnectionState
type V1alpha1ConnectionState struct {

	// attempted at
	AttemptedAt *V1Time `json:"attemptedAt,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this v1alpha1 connection state
func (m *V1alpha1ConnectionState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttemptedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1alpha1ConnectionState) validateAttemptedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.AttemptedAt) { // not required
		return nil
	}

	if m.AttemptedAt != nil {
		if err := m.AttemptedAt.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("attemptedAt")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ConnectionState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ConnectionState) UnmarshalBinary(b []byte) error {
	var res V1alpha1ConnectionState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
