// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1ApplicationDestination ApplicationDestination contains deployment destination information
//
// swagger:model v1alpha1ApplicationDestination
type V1alpha1ApplicationDestination struct {

	// Namespace overrides the environment namespace value in the ksonnet app.yaml
	Namespace string `json:"namespace,omitempty"`

	// Server overrides the environment server value in the ksonnet app.yaml
	Server string `json:"server,omitempty"`
}

// Validate validates this v1alpha1 application destination
func (m *V1alpha1ApplicationDestination) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1ApplicationDestination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1ApplicationDestination) UnmarshalBinary(b []byte) error {
	var res V1alpha1ApplicationDestination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
