// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1JsonnetVar JsonnetVar is a jsonnet variable
//
// swagger:model v1alpha1JsonnetVar
type V1alpha1JsonnetVar struct {

	// code
	Code bool `json:"code,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this v1alpha1 jsonnet var
func (m *V1alpha1JsonnetVar) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1JsonnetVar) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1JsonnetVar) UnmarshalBinary(b []byte) error {
	var res V1alpha1JsonnetVar
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
