// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// GetMixin3Reader is a Reader for the GetMixin3 structure.
type GetMixin3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMixin3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMixin3OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMixin3OK creates a GetMixin3OK with default headers values
func NewGetMixin3OK() *GetMixin3OK {
	return &GetMixin3OK{}
}

/*GetMixin3OK handles this case with default header values.

(empty)
*/
type GetMixin3OK struct {
	Payload *models.V1alpha1Repository
}

func (o *GetMixin3OK) Error() string {
	return fmt.Sprintf("[GET /api/v1/repositories/{repo}][%d] getMixin3OK  %+v", 200, o.Payload)
}

func (o *GetMixin3OK) GetPayload() *models.V1alpha1Repository {
	return o.Payload
}

func (o *GetMixin3OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1Repository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
