// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAppsParams creates a new ListAppsParams object
// with the default values initialized.
func NewListAppsParams() *ListAppsParams {
	var ()
	return &ListAppsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAppsParamsWithTimeout creates a new ListAppsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAppsParamsWithTimeout(timeout time.Duration) *ListAppsParams {
	var ()
	return &ListAppsParams{

		timeout: timeout,
	}
}

// NewListAppsParamsWithContext creates a new ListAppsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAppsParamsWithContext(ctx context.Context) *ListAppsParams {
	var ()
	return &ListAppsParams{

		Context: ctx,
	}
}

// NewListAppsParamsWithHTTPClient creates a new ListAppsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAppsParamsWithHTTPClient(client *http.Client) *ListAppsParams {
	var ()
	return &ListAppsParams{
		HTTPClient: client,
	}
}

/*ListAppsParams contains all the parameters to send to the API endpoint
for the list apps operation typically these are written to a http.Request
*/
type ListAppsParams struct {

	/*Repo*/
	Repo string
	/*Revision*/
	Revision *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list apps params
func (o *ListAppsParams) WithTimeout(timeout time.Duration) *ListAppsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list apps params
func (o *ListAppsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list apps params
func (o *ListAppsParams) WithContext(ctx context.Context) *ListAppsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list apps params
func (o *ListAppsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list apps params
func (o *ListAppsParams) WithHTTPClient(client *http.Client) *ListAppsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list apps params
func (o *ListAppsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRepo adds the repo to the list apps params
func (o *ListAppsParams) WithRepo(repo string) *ListAppsParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the list apps params
func (o *ListAppsParams) SetRepo(repo string) {
	o.Repo = repo
}

// WithRevision adds the revision to the list apps params
func (o *ListAppsParams) WithRevision(revision *string) *ListAppsParams {
	o.SetRevision(revision)
	return o
}

// SetRevision adds the revision to the list apps params
func (o *ListAppsParams) SetRevision(revision *string) {
	o.Revision = revision
}

// WriteToRequest writes these params to a swagger request
func (o *ListAppsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if o.Revision != nil {

		// query param revision
		var qrRevision string
		if o.Revision != nil {
			qrRevision = *o.Revision
		}
		qRevision := qrRevision
		if qRevision != "" {
			if err := r.SetQueryParam("revision", qRevision); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
