// Code generated by go-swagger; DO NOT EDIT.

package repository_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// ValidateAccessReader is a Reader for the ValidateAccess structure.
type ValidateAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ValidateAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewValidateAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewValidateAccessOK creates a ValidateAccessOK with default headers values
func NewValidateAccessOK() *ValidateAccessOK {
	return &ValidateAccessOK{}
}

/*ValidateAccessOK handles this case with default header values.

(empty)
*/
type ValidateAccessOK struct {
	Payload models.RepositoryRepoResponse
}

func (o *ValidateAccessOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/repositories/{repo}/validate][%d] validateAccessOK  %+v", 200, o.Payload)
}

func (o *ValidateAccessOK) GetPayload() models.RepositoryRepoResponse {
	return o.Payload
}

func (o *ValidateAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
