// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// DeleteMixin6Reader is a Reader for the DeleteMixin6 structure.
type DeleteMixin6Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMixin6Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMixin6OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteMixin6OK creates a DeleteMixin6OK with default headers values
func NewDeleteMixin6OK() *DeleteMixin6OK {
	return &DeleteMixin6OK{}
}

/*DeleteMixin6OK handles this case with default header values.

(empty)
*/
type DeleteMixin6OK struct {
	Payload models.ProjectEmptyResponse
}

func (o *DeleteMixin6OK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/projects/{name}][%d] deleteMixin6OK  %+v", 200, o.Payload)
}

func (o *DeleteMixin6OK) GetPayload() models.ProjectEmptyResponse {
	return o.Payload
}

func (o *DeleteMixin6OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
