// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMixin6Params creates a new GetMixin6Params object
// with the default values initialized.
func NewGetMixin6Params() *GetMixin6Params {
	var ()
	return &GetMixin6Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMixin6ParamsWithTimeout creates a new GetMixin6Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMixin6ParamsWithTimeout(timeout time.Duration) *GetMixin6Params {
	var ()
	return &GetMixin6Params{

		timeout: timeout,
	}
}

// NewGetMixin6ParamsWithContext creates a new GetMixin6Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetMixin6ParamsWithContext(ctx context.Context) *GetMixin6Params {
	var ()
	return &GetMixin6Params{

		Context: ctx,
	}
}

// NewGetMixin6ParamsWithHTTPClient creates a new GetMixin6Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMixin6ParamsWithHTTPClient(client *http.Client) *GetMixin6Params {
	var ()
	return &GetMixin6Params{
		HTTPClient: client,
	}
}

/*GetMixin6Params contains all the parameters to send to the API endpoint
for the get mixin6 operation typically these are written to a http.Request
*/
type GetMixin6Params struct {

	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get mixin6 params
func (o *GetMixin6Params) WithTimeout(timeout time.Duration) *GetMixin6Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mixin6 params
func (o *GetMixin6Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mixin6 params
func (o *GetMixin6Params) WithContext(ctx context.Context) *GetMixin6Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mixin6 params
func (o *GetMixin6Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mixin6 params
func (o *GetMixin6Params) WithHTTPClient(client *http.Client) *GetMixin6Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mixin6 params
func (o *GetMixin6Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get mixin6 params
func (o *GetMixin6Params) WithName(name string) *GetMixin6Params {
	o.SetName(name)
	return o
}

// SetName adds the name to the get mixin6 params
func (o *GetMixin6Params) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetMixin6Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
