// Code generated by go-swagger; DO NOT EDIT.

package cluster_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rhd-gitops-examples/gitops-backend/pkg/argocd/models"
)

// RotateAuthReader is a Reader for the RotateAuth structure.
type RotateAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RotateAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRotateAuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRotateAuthOK creates a RotateAuthOK with default headers values
func NewRotateAuthOK() *RotateAuthOK {
	return &RotateAuthOK{}
}

/*RotateAuthOK handles this case with default header values.

(empty)
*/
type RotateAuthOK struct {
	Payload models.ClusterClusterResponse
}

func (o *RotateAuthOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/clusters/{server}/rotate-auth][%d] rotateAuthOK  %+v", 200, o.Payload)
}

func (o *RotateAuthOK) GetPayload() models.ClusterClusterResponse {
	return o.Payload
}

func (o *RotateAuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
